# Application Configuration File
# Fill in the required fields below and customize as needed

[fub]
api_key = ""
seller_smartlist_id = ""
excluded_stages = ["stage1", "stage2"]

[mls]
user = ""
pass = ""

[smtp]
  user = ""
  pass = ""
  from = ""
  addresses = ["test@example.com"]
  host = "127.0.0.1"
  port = "1025"
